{
 "title": "Main",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Consensus", "type": "row", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Chain height",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 1 },
   "targets": [
    { "expr": "namada_tm_consensus_height", "legendFormat": "{{job}}" },
    {
     "expr": "sum(namada_tm_consensus_height)/ count(count by (job) (namada_tm_consensus_height))",
     "legendFormat": "mean"
    }
   ]
  },
  {
   "title": "Chain size (#txs)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 8 },
   "targets": [
    { "expr": "namada_tm_consensus_total_txs", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Block size (kb)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "namada_tm_consensus_block_size_bytes/1024",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Round number",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 19 },
   "targets": [
    { "expr": "namada_tm_consensus_rounds", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "P2P",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sent kb per message type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "(sum(rate(namada_tm_p2p_message_send_bytes_total[1m])) by (message_type))/1024",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Received kb per message type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "(sum(rate(namada_tm_p2p_message_receive_bytes_total[1m])) by (message_type))/1024",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of peers",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 18 },
     "targets": [
      { "expr": "namada_tm_p2p_peers", "legendFormat": "{{job}}" }
     ]
    }
   ]
  },
  {
   "title": "Mempool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mempool size (#txs)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 3 },
     "targets": [
      { "expr": "namada_tm_mempool_size", "legendFormat": "{{job}}" }
     ]
    },
    {
     "title": "Size of txs (kb) added to the mempool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "rate(namada_tm_mempool_tx_size_bytes_sum[$__rate_interval])/2014",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Received kb (only mempool messages)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "rate(namada_tm_p2p_message_receive_bytes_total{message_type=~\"mempool_Txs|mempool_Message|mempool_WantTx|mempool_SeenTx\"}[$__rate_interval])/1024",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Sent kb (only mempool messages)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "rate(namada_tm_p2p_message_send_bytes_total{message_type=~\"mempool_Txs|mempool_Message|mempool_SeenTx|mempool_WantTx\"}[$__rate_interval])/1024",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Recheck rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "sum(rate(namada_tm_mempool_recheck_times[1m])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Already received txs (rate)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "rate(namada_tm_mempool_already_received_txs[$__rate_interval])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Txs rejected by the app (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 73 },
     "targets": [
      {
       "expr": "namada_tm_mempool_failed_txs / (namada_tm_mempool_failed_txs + namada_tm_consensus_total_txs) * 100",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "BlockSync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Block syncing",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 18, "x": 0, "y": 4 },
     "targets": [
      { "expr": "namada_tm_blocksync_syncing", "legendFormat": "{{job}}" }
     ]
    }
   ]
  }
 ]
}