{
 "title": "Mempool [compact]",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Consensus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Chain height",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "min(namada_tm_consensus_height)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Chain size (#txs)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "min(namada_tm_consensus_total_txs)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(namada_tm_consensus_block_size_bytes)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Block size (#txs)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "avg(namada_tm_consensus_num_txs)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "P2P", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Sent kb per message type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(namada_tm_p2p_message_send_bytes_total{message_type=~\"consensus_BlockPart\"}[$__rate_interval])) by (message_type)/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(namada_tm_p2p_message_send_bytes_total{message_type=~\"mempool_Txs|mempool_SeenTx|mempool_WantTx\"}[$__rate_interval]))/1024",
     "legendFormat": "mempool_*"
    }
   ]
  },
  {
   "title": "Received kb per message type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 15 },
   "targets": [
    {
     "expr": "sum(rate(namada_tm_p2p_message_receive_bytes_total{message_type=~\"consensus_BlockPart\"}[$__rate_interval])) by (message_type)/1024",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(sum(rate(namada_tm_p2p_message_receive_bytes_total{message_type=~\"mempool_Txs|mempool_SeenTx|mempool_WantTx\"}[$__rate_interval])) by (message_type)))/1024",
     "legendFormat": "mempool_*"
    }
   ]
  },
  { "title": "Mempool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Avg. size of txs added to mempools (kb)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg(rate(namada_tm_mempool_tx_size_bytes_sum[$__interval])/1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg. mempool size (#txs)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 24 },
   "targets": [
    { "expr": "avg(namada_tm_mempool_size)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Sent kb (only mempool messages)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "(sum(rate(namada_tm_p2p_message_send_bytes_total{message_type=~\"mempool_Txs|mempool_Message|mempool_SeenTx|mempool_WantTx\", job=\"validator001\"}[$__rate_interval])))/1024",
     "legendFormat": "validator receiving all load"
    },
    {
     "expr": "(avg(rate(namada_tm_p2p_message_send_bytes_total{message_type=~\"mempool_Txs|mempool_Message|mempool_SeenTx|mempool_WantTx\", job!=\"validator001\"}[$__rate_interval])))/1024",
     "legendFormat": "avg. of other validators"
    }
   ]
  },
  {
   "title": "Received kb (only mempool messages)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 31 },
   "targets": [
    {
     "expr": "(sum(rate(namada_tm_p2p_message_receive_bytes_total{message_type=~\"mempool_Txs|mempool_Message|mempool_WantTx|mempool_SeenTx\", job=\"validator001\"}[$__rate_interval])))/1024",
     "legendFormat": "validator receiving all load"
    },
    {
     "expr": "(avg(rate(namada_tm_p2p_message_receive_bytes_total{message_type=~\"mempool_Txs|mempool_Message|mempool_WantTx|mempool_SeenTx\", job!=\"validator001\"}[$__rate_interval])))/1024",
     "legendFormat": "avg. of other validators"
    }
   ]
  },
  {
   "title": "Recheck rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(namada_tm_mempool_recheck_times{job=\"validator001\"}[$__rate_interval]))",
     "legendFormat": "validator receiving all load"
    },
    {
     "expr": "avg(rate(namada_tm_mempool_recheck_times{job!=\"validator001\"}[$__rate_interval]))",
     "legendFormat": "avg. of other validators"
    }
   ]
  },
  {
   "title": "Already received txs",
   "type": "timeseries",
   "description": "Number of received txs that hit the cache.",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 38 },
   "targets": [
    {
     "expr": "sum(rate(namada_tm_mempool_already_received_txs{job=\"validator001\"}[$__rate_interval]))",
     "legendFormat": "validator receiving all load"
    },
    {
     "expr": "avg(rate(namada_tm_mempool_already_received_txs{job!=\"validator001\"}[$__rate_interval]))",
     "legendFormat": "avg. of other validators"
    }
   ]
  }
 ]
}